#!/usr/bin/python3
# PYTHON_ARGCOMPLETE_OK
import argparse
import batchfilemanage


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='batch file manager')
    subparsers = parser.add_subparsers(dest='command', description='command to be called', required=True)

    ## create arg parsers for each subcommands
    batchfilemanage.cbz.create_args(subparsers)
    batchfilemanage.crop.create_args(subparsers)
    batchfilemanage.cut.create_args(subparsers)
    batchfilemanage.move.create_args(subparsers)
    batchfilemanage.number.create_args(subparsers)
    batchfilemanage.remove.create_args(subparsers)
    batchfilemanage.rename.create_args(subparsers)

    ## use argcomplete if available in python env
    try:
        import argcomplete
        argcomplete.autocomplete(parser)
    except:
        pass
    args = parser.parse_args()

    ## call mains accordingly
    if args.command == 'cbz': batchfilemanage.cbz.main(args)
    if args.command == 'crop': batchfilemanage.crop.main(args)
    if args.command == 'cut': batchfilemanage.cut.main(args)
    if args.command == 'move': batchfilemanage.move.main(args)
    if args.command == 'number': batchfilemanage.number.main(args)
    if args.command == 'remove': batchfilemanage.remove.main(args)
    if args.command == 'rename': batchfilemanage.rename.main(args)
